[docs] Replace `randn` -> `rand` in example to limit module of noise
`randn` distribution is virtually unbound, potentially leading to very
large (>> 1) values, causing possible numerical issues, e.g.

```
ERROR: LoadError: DomainError with -0.2590382167228948:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
Stacktrace:
  [1] throw_exp_domainerror(x::Float64)
    @ Base.Math ./math.jl:41
  [2] ^(x::Float64, y::Float64)
    @ Base.Math ./math.jl:1155
  [3] saturation_vapor_pressure
    @ ~/.julia/dev/Breeze/src/Thermodynamics/vapor_saturation.jl:33 [inlined]
  [4] saturation_specific_humidity
    @ ~/.julia/dev/Breeze/src/Thermodynamics/vapor_saturation.jl:51 [inlined]
  [5] saturation_specific_humidity
    @ ~/.julia/dev/Breeze/src/Thermodynamics/reference_states.jl:61 [inlined]
  [6] condensate_specific_humidity(T::Float64, q::Float64, z::Float64, ref::ReferenceStateConstants{Float64}, thermo::ThermodynamicConstants{Float64, CondensedPhase{Float64}, CondensedPhase{Float64}})
    @ Breeze.Thermodynamics ~/.julia/dev/Breeze/src/Thermodynamics/reference_states.jl:65
  [7] condensate_specific_humidity
    @ ~/.julia/dev/Breeze/src/MoistAirBuoyancies.jl:236 [inlined]
  [8] temperature
    @ ~/.julia/dev/Breeze/src/MoistAirBuoyancies.jl:271 [inlined]
  [9] specific_volume
    @ ~/.julia/dev/Breeze/src/MoistAirBuoyancies.jl:314 [inlined]
 [10] buoyancy_perturbationᶜᶜᶜ
    @ ~/.julia/dev/Breeze/src/MoistAirBuoyancies.jl:105 [inlined]
 [11] ℑzᵃᵃᶠ
    @ ~/.julia/packages/Oceananigans/A56vm/src/Operators/interpolation_operators.jl:28 [inlined]
 [12] z_dot_g_bᶜᶜᶠ
    @ ~/.julia/packages/Oceananigans/A56vm/src/BuoyancyFormulations/g_dot_b.jl:4 [inlined]
```

In a previous change we fixed the RNG seed, to at least avoid issues in the
default script, but changing the seed value one could still hit this issue.
By replacing `randn` with `rand` we avoid the issue of potentially hitting
large noise values altogether.  By shifting `rand() - 0.5` we still get both
positive and negative noise values (with plain `rand` we'd get only
non-negative values).